name: Playwright Tests

# Run the pipeline on every push and pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
      - uses: actions/checkout@v3

      # Set up Node.js (same version you use locally, e.g. 18 or 20)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies (from package.json)
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers (once per pipeline)
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run the tests
      - name: Run Playwright Tests
        run: npx playwright test